---
title: "Research for development"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    self_contained: false
    social: menu
    source_code: https://git.io/JqCOd
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
library(glue)
library(leaflet)
```


```{r, echo = FALSE}

# read -----

projects <- read_csv(here("data", "projects.csv")) # p3 project data on r4d
people <- read_csv(here("data", "people.csv")) #  p3 people data on r4d
gmaps <- read_csv(here("data", "gmaps.csv")) # google maps coordinate data


# logic -----

projects <- projects %>%
  mutate(project_slug = glue("http://p3.snf.ch/project-{project_number}"))

people <- people %>%
  mutate(institute_slug = glue("http://p3.snf.ch/institute-{institute_id_p3}"))

# list of participants
institutes_in_project <- people %>%
  filter(!is.na(institute_id_p3)) %>%
  mutate(
    p3_link = glue("<a href='{institute_slug}' target='_blank' rel='noopener noreferrer'>{institute_name}</a>")) %>%
  group_by(project_number) %>%
  summarise(
    institute_list = str_c(unique(p3_link), collapse = "</li><li>"),
    .groups = "drop")

# data denormalization
denorm <- people %>% 
  left_join(projects, by = "project_number") %>%
  left_join(gmaps, by = c("institute_id_p3" = "institute_id")) %>%
  left_join(institutes_in_project, by = "project_number") %>%
  filter(!is.na(gmaps_id)) %>%
  distinct(gmaps_id, .keep_all = TRUE) %>%
  mutate(
    k_amount = as.numeric(approved_amount),
    k_amount = round(k_amount / 1000),
    funding_instrument = recode(
      funding_instrument,
      `r4d (Swiss Programme for Research on Global Issues for Development)` = "r4d"),
    content = glue(
      "<span class='label label-info'>{funding_instrument}</span> <b>{gmaps_name}</b>",
      "<hr/><a href='{project_slug}' target='_blank' rel='noopener noreferrer'>{project_title}</a><br/>",
      "<div><br/><button data-toggle='collapse' data-target='#participants'>Participants</button> ",
      "<button data-toggle='collapse' data-target='#details'>Details</button></div>",
      "<div id='participants' class='collapse'><hr/>",
      "<ul><li>",
      "{institute_list}",
      "</li></ul></div>",
      "<div id='details' class='collapse'><hr/>",
      "Start <span class='label label-default'>{start_date}</span> ",
      "End <span class='label label-default'>{end_date}</span> ",
      "Amount <span class='label label-default'>{k_amount} kchf</span>",
      "</div>"))

denorm_df <- split(denorm, pull(denorm, running))

# display ------ 

gray_markers <-  awesomeIcons(
  icon = "fa-circle",
  library = "fa",
  markerColor = rep("gray", nrow(pluck(denorm_df, 1))),
  iconColor = "white")

blue_markers <-  awesomeIcons(
  icon = "fa-circle",
  library = "fa",
  markerColor = rep("blue", nrow(pluck(denorm_df, 2))),
  iconColor = "white")

leaflet(width = "100%") %>% 
  setView(2, 20, 3.5) %>%
  addAwesomeMarkers(
    data=pluck(denorm_df, 1),
    lng=~gmaps_lng,
    lat=~gmaps_lat, 
    icon=gray_markers,
    popup=~content,
    group="inactive") %>%
  addAwesomeMarkers(
    data=pluck(denorm_df, 2),
    lng=~gmaps_lng,
    lat=~gmaps_lat, 
    icon=blue_markers,
    popup=~content,
    group="active") %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "Map") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
  addLayersControl(
    baseGroups = c("Map", "Satellite"),
    overlayGroups = c("active", "inactive"),
    options = layersControlOptions(collapsed = TRUE)) %>%
  addMiniMap(tiles = providers$Esri.WorldGrayCanvas, toggleDisplay = TRUE)
```

```{r mapbox, include=FALSE, eval=FALSE}
mapbox_access_token <- Sys.getenv("MAPBOX_KEY")
tcu_map <- paste0(
  'https://api.mapbox.com/styles/v1/',
  'mapbox/streets-v11/',
  'tiles/{z}/{x}/{y}?access_token=', 
  mapbox_access_token)
tcu_satellite <- paste0(
  'https://api.mapbox.com/styles/v1/',
  'mapbox/satellite-v9/',
  'tiles/{z}/{x}/{y}?access_token=', 
  mapbox_access_token)
map_attr <- paste0(
  'Map data &copy; ',
  '<a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> ',
  'contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>')

leaflet(data = denorm, width = "100%") %>% 
  setView(2, 20, 3.5) %>%
  addMarkers(~gmaps_lng, ~gmaps_lat, popup = ~content) %>%
  addTiles(urlTemplate = tcu_map, attribution = map_attr, group = "Map") %>%
  addTiles(urlTemplate = tcu_satellite, attribution = map_attr, group = "Satellite") %>%
  addLayersControl(
    baseGroups = c("Map", "Satellite"),
    options = layersControlOptions(collapsed = TRUE)) %>%
  addMiniMap(tiles = providers$Esri.WorldGrayCanvas, toggleDisplay = TRUE)

```

