---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Research programmes for development

<!-- badges: start -->
<!-- badges: end -->

The goal of this project is to try to map the institutes involved in the Swiss Programme for Research on Global Issues for Development ([r4d](http://www.r4d.ch/)) on the world map.

### Schema specs for research earth

#### `tags.csv`

|Attribute  |Description                       |
|:----------|:---------------------------------|
|tags_id    |Keyword unique ID                 |
|tags_name  |Keyword name                      |

#### `disciplines.csv`

|Attribute         |Description                             |
|:-----------------|:---------------------------------------|
|disciplines_id    |P3 grant id                             |
|disciplines_name  |P3 discipline name                      |
|tier              |Discipline hierarchy                    |

#### `funders.csv`

|Attribute         |Description                                |
|:-----------------|:------------------------------------------|
|funder_id         |P3 grant id                                |
|funders_name      |Family and first names of person in grant  |
|snsf              |snsf person id                             |
|role              |[Project as](role)                         |

> **snsf** is mislieading
> **funders_name** is ambiguous

#### `projects.csv`

|Attribute                 |Description                          |
|:-------------------------|:------------------------------------|
|project_id                |P3 grant id                          |
|project_name              |P3 grant title                       |
|contact_person            |PI first and last names              |
|email                     |??                                   |
|start_date                |`%b-%Y`                              |
|end_date                  |`%b-%Y`                              |
|approved_amount           |Grant size in CHF                    |
|project_description       |`r4d`, `SPIRIT`, etc. (instrument)   |
|transdisciplinary         |P3 grant title                       |
|projects_disciplines_id   |list of P3 discipline ids            |
|tag_id                    |list generated keyword ids           |
|projects_funder_id        |list of funders                      |
|projects_organizations_id |list of organisations                |

#### `organizations.csv`

|Attribute                    |Description                        |
|:----------------------------|:----------------------------------|
|organizations_id             |P3 institute number (gmap.inst_id) |
|organizations_name           |[Details](instname)                |
|lat                          |Latitude       (gmap)              |
|lng                          |Longitude      (gmap)              |
|gmaps_id                     |Google maps id                     |
|address                      |Name on google maps                |
|country                      |gmaps_coutry                       |
|website                      |to be collected                    |
|organizations_disciplines_id |list of disciplines related to org |
|organizations_funder_id      |list of linked funders             |
|partner_organizations_id     |list of linked orgs                |
|organizations_project_id     |list of linked projects            |

[role]: http://p3.snf.ch/Pages/DataAndDocumentation.aspx#Projects%20as%20responsible%20Applicant "Example"
[instname]: http://p3.snf.ch/Pages/DataAndDocumentation.aspx#Institute%20Name "Institute name"
[instplace]: http://p3.snf.ch/Pages/DataAndDocumentation.aspx#Institute%20Place "Institute place"

Explore the [raw data](https://flatgithub.com/zambujo/r4data/tree/research-earth).

## Simplified Tree
 
```
.
├── DESCRIPTION
├── LICENSE
├── install.R
├─ data
│   ├── disciplines.csv
│   ├── gmaps.csv
│   ├── people.csv
│   ├── projects.csv
│   ├── research_earth
│   │   ├── disciplines.csv
│   │   ├── funders.csv
│   │   ├── organizations.csv
│   │   ├── projects.csv
│   │   └── tags.csv
│   └── schema.svg
├── docs
│   └── index.html
├── inst
│   └── extdata
│       ├── p3-tables.yml
│       └── screenshot.jpg
├── README.md
├── README.Rmd
└── Rmd
    ├── explore.Rmd
    └── gather.Rmd

```

## License

Distributed under the MIT License.

## Acknowledgments

See list of packages in [DESCRIPTION file](./DESCRIPTION).
